# Generated by Django 3.1.7 on 2022-01-18 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_comment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('A', 'Activated'), ('D', 'Deactivated')], default='A', max_length=1, verbose_name='status'),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
